Repository 2024-2-SOLUX-in-space/inspace-frontend, pull requests merged in 2025-01, with the labels that each got.

#5 Feat: 검색 기능
  package-lock.json
  package.json
  src/App.jsx
  src/components/SearchBar.jsx
  src/img/Dummy/image_1.png
  src/img/Dummy/image_10.png
  src/img/Dummy/image_11.png
  src/img/Dummy/image_12.png
  src/img/Dummy/image_13.png
  src/img/Dummy/image_14.png
  src/img/Dummy/image_15.png
  src/img/Dummy/image_16.png
  src/img/Dummy/image_17.png
  src/img/Dummy/image_18.png
  src/img/Dummy/image_19.png
  src/img/Dummy/image_2.png
  src/img/Dummy/image_20.png
  src/img/Dummy/image_21.png
  src/img/Dummy/image_22.png
  src/img/Dummy/image_23.png
  src/img/Dummy/image_24.png
  src/img/Dummy/image_25.png
  src/img/Dummy/image_26.png
  src/img/Dummy/image_27.png
  src/img/Dummy/image_28.png
  src/img/Dummy/image_29.png
  src/img/Dummy/image_3.png
  src/img/Dummy/image_30.png
  src/img/Dummy/image_4.png
  src/img/Dummy/image_5.png
  src/img/Dummy/image_6.png
  src/img/Dummy/image_7.png
  src/img/Dummy/image_8.png
  src/img/Dummy/image_9.png
  src/img/Logo.png
  src/img/ProfileImage.png
  src/img/SearchResultImage.png
  src/img/dummyImage.png
  src/pages/Home.jsx
  src/pages/SearchResult.jsx
  src/styles/SearchResultStyles.js
Labels: feat, 🍅정연 🍅

#11 Feat: 공간(홈) 구현
  package-lock.json
  package.json
  public/cover1_back.png
  public/cover1_front.png
  public/cover2_back.png
  public/cover2_front.png
  public/cover3_back.png
  public/cover3_front.png
  src/components/EditSidebar.jsx
  src/components/HomeDiary.jsx
  src/components/ImageAddModal.jsx
  src/components/PageItem.jsx
  src/pages/Home.jsx
  src/styles/EditSidebarStyle.js
  src/styles/HomeDiaryStyle.js
  src/styles/HomeStyle.js
Labels: feat, 🍄예빈🍄

#10 Feat: 사이드바 토글 및 호버 기능
  public/archive-pin.png
  public/pinbutton.png
  src/App.css
  src/App.jsx
  src/components/ArchiveButton.jsx
  src/components/FixModel.jsx
  src/components/MenuSidebar.jsx
  src/components/SwitchModel.jsx
  src/components/TrashAlert.jsx
  src/components/TrashModel.jsx
  src/styles/ArchiveButtonStyle.js
  src/styles/FixModelStyle.js
  src/styles/MenuSidebarStyle.js
  src/styles/SwitchModelStyle.js
  src/styles/TrashModelStyle.js
Labels: feat, 🍊채연🍊

#17 Fix: 회원가입 페이지
  src/components/LogInTextField.jsx
  src/components/TextField.jsx
  src/pages/SignUpPage.jsx
  src/styles/TextFieldStyle.js
Labels: ☕채현☕, fix

#14 Fix: Header
  src/components/Notification.jsx
  src/components/SearchBar.jsx
  src/pages/SearchResult.jsx
Labels: 🍄예빈🍄, fix

#18 Feat: 마이페이지
  src/App.jsx
  src/assets/EditProfileLogo.png
  src/assets/ProfileLogo.png
  src/components/SearchBar.jsx
  src/context/UserContext.jsx
  src/pages/LogInPage.jsx
  src/pages/MyPage.jsx
  src/pages/MyPageEdit.jsx
  src/styles/MyPageEditStyle.js
  src/styles/MyPageStyle.js
Labels: feat, ☕채현☕

#30 API: 회원가입, 로그인, 비밀번호찾기
  src/api/api.js
  src/components/user/LogInTextField.jsx
  src/components/user/TextField.jsx
  src/context/UserContext.jsx
  src/pages/StartPage.jsx
  src/pages/user/EditMyPage.jsx
  src/pages/user/ForgotPasswordPage.jsx
  src/pages/user/LogInPage.jsx
  src/pages/user/MyPage.jsx
  src/pages/user/SignUpPage.jsx
  src/styles/StartPageStyle.js
  src/styles/user/ForgotPasswordPageStyle.js
  src/styles/user/LogInPageStyle.js
  src/styles/user/LogInTextFieldStyle.js
  src/styles/user/SignUpPageStyle.js
  src/styles/user/TextFieldStyle.js
Labels: ☕채현☕, api

#33 API: 마이페이지, 내 정보 수정
  src/pages/user/EditMyPage.jsx
  src/pages/user/MyPage.jsx
Labels: ☕채현☕, api
