Repository 2024-2-SOLUX-in-space/inspace-frontend, pull requests merged in 2025-02, with the labels that each got.

#35 API: 공간 추가, 팔로워/팔로잉 목록, 팔로우/언팔로우, 실시간 알림
  package-lock.json
  package.json
  src/components/Header.jsx
  src/components/alert/Notification.jsx
  src/components/sidebar/AddButton.jsx
  src/components/sidebar/CoverSelection.jsx
  src/components/sidebar/HeartButton.jsx
  src/components/sidebar/NameInput.jsx
  src/components/sidebar/PublicSelection.jsx
  src/styles/sidebar/HeartButtonStyle.js
  src/styles/sidebar/NameInputStyle.js
Labels: 🍊채연🍊, api

#36 Api: 공간(홈) 관련 api들
  package-lock.json
  package.json
  public/home/bear1.png
  public/home/bear2.png
  public/home/bear3.png
  public/home/diary.png
  public/home/music1.png
  public/home/music2.png
  public/home/music3.png
  public/home/youtube1.png
  public/home/youtube2.png
  public/home/youtube3.png
  scripts/generateStickerData.js
  src/App.jsx
  src/api/space.js
  src/components/home/EditSidebar.jsx
  src/components/home/HomeDiary.jsx
  src/components/home/Page.jsx
  src/components/home/PageCover.jsx
  src/components/home/PageItem.jsx
  src/components/sidebar/AddButton.jsx
  src/components/sidebar/ArchiveButton.jsx
  src/components/sidebar/CoverSelection.jsx
  src/components/sidebar/EditButton.jsx
  src/components/sidebar/FixModal.jsx
  src/components/sidebar/HeartButton.jsx
  src/components/sidebar/HomeButton.jsx
  src/components/sidebar/SwitchModal.jsx
  src/components/sidebar/TrashModal.jsx
  src/context/ItemContext.jsx
  src/context/SpaceContext.jsx
  src/pages/MenuSidebar.jsx
  src/pages/home/Home.jsx
  src/pages/home/HomeDiary.jsx
  src/pages/home/HomePage.jsx
  src/pages/home/ImageAddModal.jsx
  src/pages/user/LogInPage.jsx
  src/styles/home/EditSidebarStyle.js
  src/styles/sidebar/ArchiveButtonStyle.js
  src/styles/sidebar/CoverSelectionStyle.js
  src/styles/sidebar/NameInputStyle.js
  tree_structure.txt
Labels: 🍄예빈🍄, api

#39 fix: 에러 수정
  package-lock.json
  package.json
  src/App.jsx
  src/api/space.js
  src/components/home/EditSidebar.jsx
  src/components/home/HomeDiary.jsx
  src/components/home/Page.jsx
  src/components/home/PageCover.jsx
  src/components/home/PageItem.jsx
  src/components/sidebar/AddButton.jsx
  src/components/sidebar/ArchiveButton.jsx
  src/components/sidebar/CoverSelection.jsx
  src/components/sidebar/PublicSelection.jsx
  src/components/sidebar/TrashModal.jsx
  src/context/SpaceContext.jsx
  src/pages/MenuSidebar.jsx
  src/pages/home/Home.jsx
  src/pages/home/ImageAddModal.jsx
  src/pages/user/LogInPage.jsx
  src/pages/user/MyPage.jsx
  src/redux/actions/spaceActions.js
  src/redux/reducers/authReducer.js
  src/redux/reducers/spaceReducer.js
  src/redux/store.js
Labels: 🍄예빈🍄, fix

#40 fix: 로그인, 로그아웃 에러, 공간 추가
  src/components/home/HomeDiary.jsx
  src/components/home/PageCover.jsx
  src/components/sidebar/AddButton.jsx
  src/components/sidebar/ArchiveButton.jsx
  src/pages/MenuSidebar.jsx
  src/pages/home/Home.jsx
  src/pages/user/LogInPage.jsx
  src/pages/user/MyPage.jsx
Labels: 🍄예빈🍄, fix

#41 Fix: 마이페이지, 내 정보 수정
  src/context/UserContext.jsx
  src/pages/user/EditMyPage.jsx
  src/pages/user/LogInPage.jsx
  src/pages/user/MyPage.jsx
Labels: ☕채현☕, api
